### ISSUE TITLE
Cannot read properties of undefined (reading 'description')

### ISSUE THREAD

**Issue by blueyshark** [samuri51/chillybot#62]
```
(node:1632) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
unable to join the room the room due to: TypeError: Cannot read properties of undefined (reading 'description')
```

Hello there. Trying to run chillybot in a 'deepcuts' room - it throws those errors at me. The odd thing is, I could get it to work a couple of times but now it just send up an error. I'm running the bot on a debian server.

Any ideas? Thanks.

**Comment by blueyshark** [comment]
That seems to have worked. The bot in question is 'philharmony' in the Hosono Lounge. It used to be run by the golang bot, but the dev seems to have run out of time to work on it any longer, so I'm giving Chilly a try, thanks.

**Comment by samuri51** [comment]
its reading in null data for some reason. ill have to take a look later to see if the site metadata changed. for now u can keep adding those question marks to the things it says, that will make it stop evaluating a null expression at that point.

ie it cant read the name property of description because description doesnt exist for some reason.

these errors are in the room changed event

**Comment by blueyshark** [comment]
OK I'll give it a try. Thanks for such a swift response, was not expecting it and that's very generous of you.

**Comment by blueyshark** [comment]
Right; it did work for me too, briefly. It stopped working again once I booted the bot and tried to run the script again.

**Comment by samuri51** [comment]
weird, it shouldn't be working intermittently unless smethings messed up on the site end.

i see the api hasnt changed in like 3 years so that either works or not 

if u have a pc running windows u can try to run it from there to eliminate something in your linux environment

shouldnt be an issue tho...

im running mine from gcp and its been fine. albeit i only go to the site nowadays like once every couple months

**Comment by samuri51** [comment]
![Untitled](https://github.com/samuri51/chillybot/assets/1833445/222f4b35-ec30-4aaa-9b52-b8f4679b6872)

metadata is lookin good here. i got someone to try on and their bot too and they don't have a problem. i'm guessing there's something wrong with the way your environment is set up

**Comment by blueyshark** [comment]
Interesting thanks. I'm using [dietpi](https://dietpi.com/), a paired down version of debian for sbcs (although my server is an old thin client). 
When I was using a golang bot, I was able to install the GO runtime using dietpi's installer script, and only do a little customising to get it all working. Hopefully I can manage the same thing here!
Would you have a vague idea where I could start, when checking and setting environment for the js?
Appreciate your speedy replies 🙌

**Comment by samuri51** [comment]
i guess i would start with making sure the js version of the ttapj is being used and not the golang one.

not totally sure tbh, the things always kinda just worked! lol

**Comment by samuri51** [comment]
another idea... run it from a docker container, thats how it runs in the cloud.

also make sure the pi can contact the website

ive had ppl running the thing from a pi before and its worked fine so im not sure why it wouldnt work

**Comment by samuri51** [comment]
[package.json](https://github.com/samuri51/chillybot/files/14998360/package.json)
[package-lock.json](https://github.com/samuri51/chillybot/files/14998362/package-lock.json)

im sending the dependcy files in case that helps

**Comment by blueyshark** [comment]
So I have chillybot running in a docker, great, thanks for the pointer.
But it seems to be ignoring `var getonstage = true;`
I have `var whenToGetOnStage = 2;`

**Comment by samuri51** [comment]
whentogetoffstage has to be at least two higher than on because the bot counts as one person.

it also doesnt kick in unless autodjing is enabled

/autodj puts the bot on manually and i believe if autondj is on the bot jumps on once stage users drop to zero

interesting about the error. docker is like a shell, the container it runs in still has to allow it to do its thing.

if u got another pc i would try running it from there to eliminate some network issue

if its debian i cant help much, not an expert on that

gcp has a free project tier tho and thats what i use as an option

**Comment by blueyshark** [comment]
SO, it must be something external. As this morning, I attempt to start chillybot, and hey presto, it works as normal. I won't boot the bot, as it seems that this causes the issue. Maybe something worth investigating?

**Comment by samuri51** [comment]
ignoring them? if you type /botstatus does it say theyre enabled?

**Comment by blueyshark** [comment]
I think we can close this issue.
- Running the bot in a docker container has helped in terms of dependencies
- When making changes to chillybot.js you must rebuild the container for the changes to be applied.
- Booting the bot from the room means the bot cannot re-enter the room right away (`unable to join the room the room due to: TypeError: Cannot read property 'description' of undefined`) - possibly there's a cooldown of some sort

Thanks again @samuri51 for all you assistance!

**Comment by blueyshark** [comment]
I think we can close this issue.
- Running the bot in a docker container has helped in terms of dependencies
- When making changes to chillybot.js you must rebuild the container for the changes to be applied.
- Booting the bot from the room means the bot cannot re-enter the room right away (`unable to join the room the room due to: TypeError: Cannot read property 'description' of undefined`) - possibly there's a cooldown of some sort

Thanks again @samuri51 for all you assistance!
